language: java
before_install:
  - mkdir ~/junit
  - ln -s /usr/share/java/junit4.jar ~/junit
  - ln -s /usr/share/java/hamcrest-core.jar ~/junit
  - export JUNIT_HOME=~/junit

install: ant test

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      - junit4