title: "JPF Core Documentation"
description: "Java Pathfinder documentation migrated from Wiki"
theme: minima   # GitHub provides minima theme by default
markdown: kramdown

# Optional: If your site is published at /jpf-core/
baseurl: /jpf-core
url: https://anniemandal24.github.io

# Navigation (optional if you want sidebar links)
plugins:
  - jekyll-feed
