name: Publish JPF Documentation to GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - add-install-docs
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: source

      # 2. Build the Jekyll site from docs/
      - name: Setup Ruby and build Jekyll
        working-directory: source/docs
        run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle install
          bundle exec jekyll build \
            --source . \
            --destination ../built-site \
            --baseurl /jpf-core

      # 3. Checkout Pages repo
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v4
        with:
          repository: Mahmoud-Khawaja/Mahmoud-Khawaja.github.io
          token: ${{ secrets.DOCS_PAT }}
          ref: main
          path: target

      # 4. Prepare target
      - name: Prepare target directory
        run: |
          rm -rf target/jpf-core
          mkdir -p target/jpf-core

      # 5. Copy built HTML and assets
      - name: Copy generated site
        run: |
          cp -r source/built-site/* target/jpf-core/

      # 6. Commit & push
      - name: Commit and push changes
        run: |
          cd target
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jpf-core
          if git diff --staged --quiet; then
            echo "No changes to deploy"
            exit 0
          fi
          git commit -m "Update JPF documentation from ${{ github.sha }}"
          git push origin main
