name: Publish JPF Documentation to GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - add-install-docs
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout jpf-core source (your docs)
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: source

      # 2. Checkout your Pages repo
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v4
        with:
          repository: Mahmoud-Khawaja/Mahmoud-Khawaja.github.io
          token: ${{ secrets.DOCS_PAT }}
          ref: main
          path: target

      # 3. Prepare a clean target directory
      - name: Prepare target directory
        run: |
          rm -rf target/jpf-core
          mkdir -p target/jpf-core

      # 4. Copy all docs (including graphics)
      - name: Copy documentation files
        run: |
          cp -r source/docs/* target/jpf-core/

      # 5. Commit & push if there are changes
      - name: Commit and push changes
        run: |
          cd target
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to deploy"
            exit 0
          fi
          git commit -m "Update JPF-core documentation from commit ${{ github.sha }}"
          git push origin main
